### ISSUE TITLE
graph lines disappearing

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/cabana-issues#16]
the graph plot disappears after selecting a segment. it reappears after selecting a segment of the segment

**Comment by adeebshihadeh** [comment]
here's a video - https://youtu.be/-zzQKSuIA-A

I also noticed that resetting the segment then selecting a segment doesn't have the issue. it only happens the first time you select a segment

**Comment by andyh2** [comment]
Fixed as of this afternoon. Thanks for the report!
