### ISSUE TITLE
cabana video and can sink log download

### ISSUE THREAD

**Issue by johnwaynehacker** [commaai/cabana-issues#19]
How can I download and save the CAN data and video sync as a dataset? I want to test the function on the computer, for example for Cabana I can record video and sync it.

Where does the video store? on the cloud , or how do it make it store on local drive and with sync can data?

**Comment by martinl** [comment]
check https://github.com/commaai/chffr-api

**Comment by arfahkT** [comment]
Is the chffr-api link working?

**Comment by arfahkT** [comment]
same question!
