### ISSUE TITLE
little endian in Cabana vs OpenPilot

### ISSUE THREAD

**Issue by adhintz** [commaai/cabana-issues#21]
OP and cabana do not treat little endian signals the same way. For example, using little endian in Cabana for this signal displays  as expected in Cabana:
`SG_ PRNDL : 0|3@1+ (1,0) [0|7] "" XXX
`
However when OpenPilot's CanParser then uses the signal from the DBC, such as a carstate.py doing cp.vl['GEAR']['PRNDL'] then the data is not correct.

Changing the Cabana signal to big endian displays fine in Cabana and is handled the same way in OpenPilot's CanParser:
`SG_ PRNDL : 2|3@0+ (1,0) [0|7] "" XXX
`
Here's an example fix I needed for OP to have the correct data: https://github.com/adhintz/opendbc/commit/3a561007f416c01a9f05bb53032eb5eaeaccc8a6

Example route is 2d534e809790e138

**Comment by adhintz** [comment]
@energee pointed out that OP doesn't have yet have support for little endian signals: https://github.com/commaai/openpilot/commit/7c1db874a80abc13d1eb773b2c2d804be586b6c0

That would explain the issue I hit.

**Comment by energee** [comment]
We can probably close this, LE coming to openpilot in the next release or two

**Comment by dzid26** [comment]
I think this is actually issue of Cabana itself. See my details in my issue report: https://github.com/commaai/cabana-issues/issues/27 
In my and his case, the CAN message is shorter than 8bytes,

**Comment by energee** [comment]
@dzid26 See comment
