### ISSUE TITLE
Save Log does not work in macOS Chrome 67

### ISSUE THREAD

**Issue by martinl** [commaai/cabana-issues#24]
When clicking Save Log button in macOS Chrome 67, nothing happens in gui. The developer console shows following error message:

mitm.html?version=1.0.0:1 Uncaught (in promise) DOMException: Failed to get a ServiceWorkerRegistration: The user denied permission to use Service Worker.
Promise.then (async)
window.onmessage.event @ mitm.html?version=1.0.0:36

I also tried macOS Safari and Firefox, neither display the Save Log button so currently there seems to be no workaround for macOS. Please fix this

**Comment by martinl** [comment]
Got it working, the problem was "block third-party cookies option" in chrome://settings/content/cookies
fixed by adding jimmywarting.github.io to allow list

**Comment by csouers** [comment]
I'm on Chrome 73. Never had this issue or modified cookie settings. Can probably be closed.

**Comment by martinl** [comment]
I tried removing jimmywarting.github.io from Chrome third-party cookies allow list. Tested with Chrome 73 and latest 74 for macOS and the issue still exists

Developer console error with no jimmywarting.github.io allow exception, log file download does not work:
<img width="569" alt="cabana_log_export_no_third_party_cookies_allowed" src="https://user-images.githubusercontent.com/148686/56797480-781cbb80-681d-11e9-8038-554eb2a4a1b9.png">

Developer console warning with jimmywarting.github.io allow exception, log file download works:
<img width="568" alt="cabana_log_export_third_party_cookies_allowed" src="https://user-images.githubusercontent.com/148686/56797482-781cbb80-681d-11e9-8152-0399ea05cd11.png">

**Comment by martinl** [comment]
The need for whitelisting depends on Chrome Block third-party cookies setting:

<img width="680" alt="Screenshot 2019-05-01 at 10 02 52" src="https://user-images.githubusercontent.com/148686/57008410-9822f500-6bf8-11e9-8c96-05720c65c078.png">

I think this can be closed
