### ISSUE TITLE
Cabana incorrect little endian calculation

### ISSUE THREAD

**Issue by dzid26** [commaai/cabana-issues#27]
### I think it may be caused by the fact my CAN message is 7byte long and Cabana gets confused.

I have one byte that never changes value (i.e. constant 0xfc ), but Cabana plots it as changing values as if it took different byte for the calculation. The problem is only with little-endian.

![image](https://user-images.githubusercontent.com/841061/44701761-4a992b80-aa5e-11e8-81e7-142eb39a86eb.png)

The problem doesn't occur in shared link!!! In shared link, unused bytes are filled with zeros which mask the problem.
So here is unhelpful link to the shared drive:
https://community.comma.ai/cabana/?route=6271bd47902a2f41%7C2018-08-04--13-01-29&max=4&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F6271bd47902a2f41%2F68680b96b9bdd9fbeef38212a3ed4308_2018-08-04--13-01-29

In shared link problem doesn't occur:
![image](https://user-images.githubusercontent.com/841061/44800581-be355880-ab84-11e8-9e2b-17f3a631ab2b.png)

**Comment by energee** [comment]
This looks like a signed value

**Comment by dzid26** [comment]
No. It's constant 0xfc - it shouldn't be changing on the plot! https://comma.slack.com/archives/C63TRR6DT/p1535558024000100

**Comment by energee** [comment]
Can you record a longer drive? like 5mins+

**Comment by dzid26** [comment]
What for? I don't think it will add any value. I have other drives, but the problem is not reproducable in shared links, because for some reason Cabana fills CAN messages that are shorter than 8bytes with zeros so that it is 8bytes long.

The bug is clear. Cabana takes wrong byte, when CAN message is not 8byte.  The only thing I can do is screenshots.

**Comment by rbiasini** [comment]
Yes, I think I identified the issue for little endian signals, in less than 8 bytes msgs. We'll deploy a fix soon.
