### ISSUE TITLE
Feature: Regex matching from filter

### ISSUE THREAD

**Issue by energee** [commaai/cabana-issues#6]
Was hoping this is a quick addition that would be really useful for viewing specific messages together in the stream

**Comment by ChristopherBiscardi** [comment]
@energee Can you supply an example regex and expected matches? My first instinct is to allow a restricted set of additional filterability that isn't regex so that we could, for example, persist the matching functionality across sessions safely.

**Comment by energee** [comment]
Hmm i think just adding the "OR" pipe so we could match a few specific IDs would be a drastic improvement. Like [e4|30c] to match 0xe4 and 0x30c.

**Comment by nmz787** [comment]
being able to supply a lambda function for filtering (and sorting) would also be nice... that way we could perform averaging on values, and filter background noise (i.e. changing data... ex: you're trying to decode a door open/closed signal).
