### ISSUE TITLE
react favicon and title

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/cabana-issues#7]
<img width="1373" alt="screen shot 2017-12-25 at 11 39 17 am" src="https://user-images.githubusercontent.com/8762862/34342545-50d1d1ee-e968-11e7-8dbf-fc45d4bbefd7.png">

**Comment by ChristopherBiscardi** [comment]
Fixed, thanks for the report. This was a result of simplifying the build process onto create-react-app.
