### ISSUE TITLE
add support for data which is from an other data source than panda

### ISSUE THREAD

**Issue by quarksteilchen** [commaai/cabana-issues#9]
panda in combination with chffr does currently not work for my car, but i can record the data with other tools. as cabana seems to be a very valuable tool to reverse-engineer canbus-data, it would be great to feed it with other sources.

or at least: is it possible to get a sample-dataset which cabana could be fed with? (e.g. (youtube?)video+can data format)

**Comment by quarksteilchen** [comment]
+label enhancement

**Comment by ChristopherBiscardi** [comment]
Hey @quarksteilchen, third party ingestion isn't on the roadmap right now but making sure panda/chffr works for your car *is* a priority. Can you list details about your car model and any additional information about the devices you're using?

**Comment by quarksteilchen** [comment]
Hi Christopher. Thanks!

I can understand that with the 3rd party ingestion. And i'm very willing to help :-).

Car: Hyundai IONIQ 2017 Hybrid with the fully digital console.
OBD2-Connector is available with this layout:
https://comma.slack.com/files/U8BTX6V5X/F8LB6BU2D/image.png
Here i mapped it to the Panda Connectors:
https://comma.slack.com/files/U8BTX6V5X/F8LN0Q6K1/image.png

When i connect Panda, it just flashes red. (after a short burst of blue wifi led blinks)
When i connect chffr to panda, the blue wifi-led goes on to a steady light.
When i drive with chffr, the panda-icon is bright white. But panda does nothing but flashing red.
When the data was uploaded, there is no cabana-link available.

So i conclude that Panda didn't find any can-buses, or didn't get the command to be enabled or starting to look for them

Other OBD2-Bluetooth-Adapters work fine.
I found out, that you also can use Panda with Android Apps like Torque.
When Torque connects to Panda, A green, cyan and yellow (maybe that's the remain of the red heartbeat) are blinking, and the wifi-led is also blinking wildly. It can read out a lot of data for my vehicle.

So, that's the state.
I would be very thankful, if we can debug further from here.

**Comment by notkaip** [comment]
+1 to being able to use a non-panda source with cabana - I have a USB CAN interface that exposes a native network interface on Linux (through SocketCAN), it would be extremely useful to be able to use cabana to build out a DBC for my car.
